Differential Methylation
========================================================

## Libraries
```{r}
setwd("/big_data/redgar/BECon")
library(reshape)
library(ggplot2)
library(RColorBrewer)
```

## Load Data
#### GSE Beta values
```{r}
load("cell_adjusted_Mcombat_Bmiq_BLBR_Beta_noreplicates_16_All.RData") #441198     64
```

#### Any meta data
```{r}
meta<-read.csv("SampleInfo.csv")
fix_names<-unlist(lapply(meta$X, function(x) gsub(" ","", x , fixed=TRUE)))
meta$X<-fix_names
meta<-meta[which(meta$X%in%colnames(combat_BLBR_Beta)),]
meta<-meta[match(colnames(combat_BLBR_Beta), meta$X),]

#M value transformation
Mval<-function(beta) log2(beta/(1-beta))
combat_BLBR_MVal = apply(combat_BLBR_Beta[,1:63], 1, Mval) # need mvalues for combat (but rm BA20221 for now cause all NA)
combat_BLBR_MVal = as.data.frame(combat_BLBR_MVal)
combat_BLBR_MVal = t(combat_BLBR_MVal)
combat_BLBR_MVal = as.data.frame(combat_BLBR_MVal)

combat_BLBR_MVal$BA20221<-NA

```



### Write DMA as Function of two tissues
```{r}
library(scales)

#PBMC, BRAIN7, BRAIN10, BRAIN20

DMA<-function(tissueA, tissueB){
  # Subset to tissueA and tissueB
  TissueAB_indx<-which(meta$TissueType%in%c(tissueA,tissueB))
  Mval_TissueAB<-combat_BLBR_MVal[,TissueAB_indx]
  combat_TissueAB<-combat_BLBR_Beta[,TissueAB_indx]
  meta_TissueAB<-meta[which(meta$X%in%colnames(Mval_TissueAB)),]
  
  p<-sapply(1:nrow(Mval_TissueAB), function(x) {
    meta_ex<-meta_TissueAB
    meta_ex$Mval<-unlist(Mval_TissueAB[x,])
    
    z<-lmer(Mval ~ TissueType+Gender+Age+(1|SubjectNumC), data=meta_ex)
    z2<-lmer(Mval ~ Gender+Age+(1|SubjectNumC), data=meta_ex)
    
    Ftest<-anova(z,z2)
    Ftest[["Pr(>Chisq)"]][2]    })
  
  hist(p)
  
  Multi_test_corr_relaxed<-p.adjust(p, method = "fdr", n = length(p))
  stat_hits<-combat_TissueAB[which(Multi_test_corr_relaxed<=0.001),] 
  print(paste("P value hits (FDR 0.001)", nrow(stat_hits), sep=": "))
  
  #Delta beta between tissues
  TissueA_BLBR<-rowMeans(combat_TissueAB[,which(meta_TissueAB$TissueType==tissueA)], na.rm=T)
  TissueB_BLBR<-rowMeans(combat_TissueAB[,which(meta_TissueAB$TissueType==tissueB)], na.rm=T)
  delbeta<-TissueA_BLBR-TissueB_BLBR
  
  bio_hits<-combat_TissueAB[which(abs(delbeta)>=0.1),] 
  print(paste("Delta Beta Hits (0.1)", nrow(bio_hits), sep=": "))
  
  save(p, Multi_test_corr_relaxed, stat_hits, delbeta, bio_hits, 
       file=paste("Results_",tissueA,tissueB,".RData", sep=""))
  }



DMA("PBMC","BRAIN10")
DMA("PBMC","BRAIN7")
DMA("PBMC","BRAIN20")
DMA("BRAIN10","BRAIN20")
DMA("BRAIN10","BRAIN7")
DMA("BRAIN20","BRAIN7")


#make the volcano plots
tissueA<-"BRAIN20"
tissueB<-"BRAIN7"

load(file=paste("DMA_results/Results_",tissueA,tissueB,".RData", sep=""))
  ## biological and statistical hits
  sta_bio_hits<-stat_hits[which(rownames(stat_hits)%in%rownames(bio_hits)),]
  print(paste("Significantly Differentially Methylated (FDR 0.001; Delta Beta 0.1)", nrow(sta_bio_hits), sep=": "))
  
  
  #VOLCANO
  volcano<-data.frame(Adjusted_Pvalue=Multi_test_corr_relaxed, Delta_Beta=delbeta)
  
  #Thresholds 
  dB<-0.1 #delta beta cutoff
  Pv<-0.001 #Pvalue cutoff
  
  sta_delbeta<-delbeta[which(Multi_test_corr_relaxed<=0.001)] 
  sta_delbeta<-sta_delbeta[abs(sta_delbeta)>=0.1]
  
  print(paste("Hypermethylated", length(sta_delbeta[which(sta_delbeta>=dB)]), sep=": "))
  print(paste("Hypomethylated", length(sta_delbeta[which(sta_delbeta<=(-dB))]) , sep=": "))
  
 ## positive delta beta is hypomethylated (code for volcano should be right now, should colors change?)
  color3<-sapply(1:nrow(volcano), function(x) if(volcano$Adjusted_Pvalue[x]<=Pv){
    if(abs(volcano$Delta_Beta[x])>dB){
      if(volcano$Delta_Beta[x]>dB){"Increased Methylation\n (Meeting Mean DNAm \nDifference Threshold)"}else{"Decreased Methylation\n (Meeting Mean DNAm \nDifference Threshold)"}
      }else{if(volcano$Delta_Beta[x]>0){"Increased Methylation"}else{"Decreased Methylation"}}}else{"Not Significantly Different"})
  volcano$Interesting_CpG3<-color3
  volcano<-volcano[which(volcano$Adjusted_Pvalue<1),]
  
  
  #omg
  volcano_plot<-ggplot(volcano, aes(Delta_Beta, -log10(Adjusted_Pvalue), color=Interesting_CpG3))+
    geom_point(shape=19, size=1)+theme_bw()+
    scale_color_manual(values=c(muted("red", l=80, c=30),"red",muted("blue", l=70, c=40),"blue","grey"),
                       name=paste("CpG Change Between \n", label1, "and", label2, sep=" "))+
    geom_vline(xintercept=c(-dB,dB), color="grey60")+
    geom_hline(yintercept=-log10(Pv), color="grey60")+
    ylab("Multiple Test Corrected P Value (-log10)")+xlab("Delta Beta")+xlim(-1, 1)+
    theme(axis.text = element_text(size =14, color="black"),
            axis.title = element_text(size =20),
            legend.text = element_text(size =14),
            legend.title = element_text(size =20))+ 
    guides(color = guide_legend(override.aes = list(size = 4)))
  ggsave(file=paste("~/Documents/Blood_Brain/DMA_results/Volcano_",tissueA,tissueB,".pdf", sep=""), plot=volcano_plot)
  ggsave(file=paste("~/Documents/Blood_Brain/DMA_results/Volcano_",tissueA,tissueB,".jpeg", sep=""), plot=volcano_plot)
```

# Table summarizing the tissue DMA hit number
```{r}
tissueA<-"BRAIN10"
tissueB<-"BRAIN7"

load(file=paste("DMA_results/Results_",tissueA,tissueB,".RData", sep=""))
sta_bio_hits<-stat_hits[which(rownames(stat_hits)%in%rownames(bio_hits)),]
print(paste("Significantly Differentially Methylated (FDR 0.001; Delta Beta 0.1)", nrow(sta_bio_hits), sep=": "))
  

data.frame(Tissue=c("BA10","BA7","BA20","PBMC"),
           BA10=c(NA,347,926,119371),
           BA7=c(NA,NA,564,123640),
           BA20=c(NA,NA,NA,120398),
           PBMC=c(NA,NA,NA,NA))

```







### Sample Correlation Heat Map
```{r}
load("cell_adjusted_Mcombat_Bmiq_BLBR_Beta_noreplicates_16_All.RData") #441198     64
meta<-read.csv("SampleInfo.csv")
fix_names<-unlist(lapply(meta$X, function(x) gsub(" ","", x , fixed=TRUE)))
meta$X<-fix_names
meta<-meta[which(meta$X%in%colnames(combat_BLBR_Beta)),]
meta<-meta[match(colnames(combat_BLBR_Beta), meta$X),]

PBMC_indx<-grep("PBMC", colnames(combat_BLBR_Beta)) #16
BRAIN7_indx<-grep("BA7", colnames(combat_BLBR_Beta)) #16 
BRAIN10_indx<-grep("BA10", colnames(combat_BLBR_Beta)) #16 
BRAIN20_indx<-grep("BA20", colnames(combat_BLBR_Beta)) #16 

PBMC_BLBR<-combat_BLBR_Beta[,PBMC_indx]
BRAIN7_BLBR<-combat_BLBR_Beta[,BRAIN7_indx]
BRAIN10_BLBR<-combat_BLBR_Beta[,BRAIN10_indx]
BRAIN20_BLBR<-combat_BLBR_Beta[,BRAIN20_indx]

# put in PBMC sample order
BRAIN7_BLBR<-BRAIN7_BLBR[,c(2,3,1,5,4,6,9,7,8,10,11,12,13,14,15,16)]
BRAIN10_BLBR<-BRAIN10_BLBR[,c(1,3,2,6,4,5,7,9,8,11,10,12,14,13,16,15)]
BRAIN20_BLBR<-BRAIN20_BLBR[,c(2,1,3,4,5,6,9,7,8,10,16,11,12,13,15,14)]

# Correlated each tissue
  mean_samp_correlation<-function(Tissue1, Tissue2){mean(sapply(1:ncol(Tissue1), function(sample)cor(Tissue1[,sample], 
                                                    Tissue2[,sample], 
                                                    use="complete.obs", 
                                                    method = "spearman")))# mean cor of samples br7 and blood
                                                    }
PBMC_B7<-mean_samp_correlation(PBMC_BLBR,BRAIN7_BLBR)
PBMC_B10<-mean_samp_correlation(PBMC_BLBR,BRAIN10_BLBR)
PBMC_B20<-mean_samp_correlation(PBMC_BLBR[,-11],BRAIN20_BLBR[,-11])
B7_B10<-mean_samp_correlation(BRAIN7_BLBR,BRAIN10_BLBR)
B7_B20<-mean_samp_correlation(BRAIN7_BLBR[,-11],BRAIN20_BLBR[,-11])
B10_B20<-mean_samp_correlation(BRAIN10_BLBR[,-11],BRAIN20_BLBR[,-11])



PLot<-data.frame(tissue1=c("Blood", "Blood","Blood","B7","B7","B10"),
                 tissue2=c("B7","B10","B20","B10","B20","B20"),
                 Correlation=c(PBMC_B7,PBMC_B10,PBMC_B20,B7_B10,B7_B20,B10_B20))

PLot$tissue1 <- factor(PLot$tissue1, levels = c("Blood","B7","B10"))
PLot$tissue2 <- factor(PLot$tissue2, levels = c("B7","B10", "B20"))

ggplot(PLot, aes(tissue1,tissue2, fill = Correlation)) +
  geom_tile(color = "black",size=0.5) +
  geom_text(aes(label = round(Correlation,3)), color="black")+theme_bw()+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
    panel.background = element_blank(), axis.line = element_blank())+
  scale_fill_continuous(limits=c(0.889, 1), low="#c6dbef", high="#4292c6")


```

