---
title: "BLBR_Enrichment"
author: "redgar"
date: '2015-02-24'
output: html_document
---
```{r}
library(ggplot2)
library(grid)
library(gridExtra)
setwd("~/Documents/Blood_Brain/")
load("cell_adjusted_Mcombat_Bmiq_BLBR_Beta_noreplicates_16_All.RData") #441198     64
combat_BLBR_Beta_adjusted<-combat_BLBR_Beta
          
          # these are already filtered
          load("Price_annotation.RData")
          Chrsex<-annotation$TargetID[which(annotation$CHR%in%c("X","Y"))]#11648
          
          load("SNPCpG.RData")
          SnpatCpG<-SNPCpG[which(SNPCpG$SNPCpG!=""),]


#1=BA7, 2=BA10, 3=BA20

load("Positively_correlated_CpGs_atreference_range_0.1_corfrom0.25_nosex_nosnp.RData")
pos_overlap<-intersect(Cor_CpGs[[1]],Cor_CpGs[[2]])
pos_overlap<-intersect(pos_overlap,Cor_CpGs[[3]])
Cor_CpGs<-unique(unlist(Cor_CpGs))


load("Negatively_correlated_CpGs_atreference_range_0.1_corfrom0.25_nosex_nosnp.RData")
neg_overlap<-intersect(negCor_CpGs[[1]],negCor_CpGs[[2]])
neg_overlap<-intersect(neg_overlap,negCor_CpGs[[3]])
negCor_CpGs<-unique(unlist(negCor_CpGs))

### should we use the overlap or the union?

```

#### Any meta data
```{r}
meta<-read.csv("~/Documents/Blood_Brain/SampleInfo.csv")
fix_names<-unlist(lapply(meta$X, function(x) gsub(" ","", x , fixed=TRUE)))
meta$X<-fix_names
meta<-meta[which(meta$X%in%colnames(combat_BLBR_Beta)),]
meta<-meta[match(colnames(combat_BLBR_Beta), meta$X),]
```

#### Any meta data
```{r}
load("Price_annotation.RData")
annotation$CpG<-rownames(annotation)
load("Gene_CpG_Relations_updatejune2015.RData")


## Hits in Features (all age associated CpGs)
Feature_Bar_Plot<-function(CpG_list){
      Genes_correlated_CpGs<-Gene_CpG_Relations_update[which(Gene_CpG_Relations_update$Probe_ID%in%CpG_list),]
      Genes_correlated_CpGs<-Genes_correlated_CpGs[!duplicated(Genes_correlated_CpGs),]
      Genes_correlated_CpGs<-Genes_correlated_CpGs[!duplicated(Genes_correlated_CpGs[,c(1,4)]),]#remove duplicate CpG to gene associations

      Gene_hits_regionMeans<-tapply(Genes_correlated_CpGs$Probe_ID, Genes_correlated_CpGs$region, length)
      Gene_hits_regionMeans<-data.frame(Probe_Count=as.numeric(Gene_hits_regionMeans), Region=names(Gene_hits_regionMeans))
      ## add a three_plus row if there were no hits in three_plus
      if("three_plus"%in%Gene_hits_regionMeans$Region){}else{
        Gene_hits_regionMeans<-rbind(Gene_hits_regionMeans,
                                     data.frame(Probe_Count=0,Region="three_plus"))}

      ## Boot strapping (to see if hits more in feature than expected)
      bootstrap_genes<-lapply(1:100, function(x){
        set.seed(x)
        Hit_number<-length(CpG_list)
        rnd_CpGs<-rownames(combat_BLBR_Beta_adjusted)[sample(1:nrow(combat_BLBR_Beta_adjusted),Hit_number)]
        Gene_rnd<-Gene_CpG_Relations_update[which(Gene_CpG_Relations_update$Probe_ID%in%rnd_CpGs),]
        Gene_rnd<-Gene_rnd[!duplicated(Gene_rnd),]
        Gene_rnd<-Gene_rnd[!duplicated(Gene_rnd[,c(1,4)]),]#remove duplicate CpG to gene associations
        Gene_rnd_regionMeans<-tapply(Gene_rnd$Probe_ID, Gene_rnd$region, length)
        Gene_rnd_regionMeans<-data.frame(Probe_Count=as.numeric(Gene_rnd_regionMeans), Region=names(Gene_rnd_regionMeans))
        if("three_plus"%in%Gene_rnd_regionMeans$Region){}else{
        Gene_rnd_regionMeans<-rbind(Gene_rnd_regionMeans,
                                     data.frame(Probe_Count=0,Region="three_plus"))}
        Gene_rnd_regionMeans})
      bootstrap_genes<-do.call(rbind,bootstrap_genes)

      Gene_mean<-tapply(bootstrap_genes$Probe_Count, bootstrap_genes$Region, mean)
      Gene_sd<-tapply(bootstrap_genes$Probe_Count, bootstrap_genes$Region, sd)
      Gene_rnd_regionMeans<-data.frame(Probe_Count=as.numeric(Gene_mean), Probe_count_SD=as.numeric(Gene_sd),
                                        Region=names(Gene_mean))
      Gene_rnd_regionMeans$Data<-paste("Random CpGs (", length(CpG_list),")", sep="")

      #Combine with real data
      Gene_hits_regionMeans$Data<-paste("Blood Brain Correlated CpGs (", length(CpG_list),")", sep="")  
      Gene_hits_regionMeans$Probe_count_SD<-0
      Gene_hits_regionMeans<-rbind(Gene_hits_regionMeans,Gene_rnd_regionMeans)
      
      Gene_hits_regionMeans$Color<-sapply(1:nrow(Gene_hits_regionMeans), function(x) {
        paste(Gene_hits_regionMeans$Region[x],Gene_hits_regionMeans$Data[x], sep=":")})
      
      Gene_hits_regionMeans$Region<-factor(Gene_hits_regionMeans$Region,
                                           levels=c("promoter","intragenic","three_plus","intergenic"))

      levels(Gene_hits_regionMeans$Region)<-c("Promoter","Intragenic","Three\nPlus","Intergenic")
      Gene<-ggplot(Gene_hits_regionMeans, aes(Region, Probe_Count, fill=Color, group=Data))+
            geom_bar(position=position_dodge(width=0.9),stat="identity", color="black")+theme_bw()+
            scale_fill_manual(values=c("#999999","#f2f2f2","#e41a1c","#fbb4ae",
                                       "#377eb8","#b3cde3","#984ea3","#decbe4"))+
            geom_errorbar(aes(ymax = Probe_Count + Probe_count_SD, ymin=Probe_Count - Probe_count_SD),
                          width=0.25,position=position_dodge(width=0.9))+ylab("Probe Count")+
        theme(axis.text = element_text(size = 12),
              axis.title = element_text(size = 14),
              legend.text = element_text(size = 12))

## CGI
      # CpGI
      CGI<-annotation[,c(58,49,50)]

      Resort_hits<-CGI[which(CGI$CpG%in%CpG_list),] #2138 CpGs, 1576 CGIs
      Resort_hits_featureMeans<-tapply(Resort_hits$CpG, Resort_hits$RELATION_TO_UCSC_CPG_ISLAND, length)
      Resort_hits_featureMeans<-data.frame(Probe_Count=as.numeric(Resort_hits_featureMeans),
                                           Feature=names(Resort_hits_featureMeans))
      levels(Resort_hits_featureMeans$Feature)<-c("None","Island","N_Shelf","N_Shore","S_Shelf","S_Shore")


      ## Boot strapping (to see if hits more in feature than expected)
      bootstrap_CGI<-lapply(1:100, function(x){
        set.seed(x)
        Hit_number<-length(CpG_list)
        rnd_CpGs<-rownames(combat_BLBR_Beta_adjusted)[sample(1:nrow(combat_BLBR_Beta_adjusted),Hit_number)]
        Resort_rnd<-CGI[which(CGI$CpG%in%rnd_CpGs),]
        Resort_rnd_featureMeans<-tapply(Resort_rnd$CpG, Resort_rnd$RELATION_TO_UCSC_CPG_ISLAND, length)
        Resort_rnd_featureMeans[which(is.na(Resort_rnd_featureMeans))]<-0
        Resort_rnd_featureMeans<-data.frame(Probe_Count=as.numeric(Resort_rnd_featureMeans),
                                            Feature=names(Resort_rnd_featureMeans))
        })
      bootstrap_CGI<-do.call(rbind,bootstrap_CGI)

      CGI_mean<-tapply(bootstrap_CGI$Probe_Count, bootstrap_CGI$Feature, mean)
      CGI_sd<-tapply(bootstrap_CGI$Probe_Count, bootstrap_CGI$Feature, sd)
      CGI_rnd_regionMeans<-data.frame(Probe_Count=as.numeric(CGI_mean), Probe_count_SD=as.numeric(CGI_sd),
                                        Feature=names(CGI_mean))
      levels(CGI_rnd_regionMeans$Feature)<-c("None","Island","N_Shelf","N_Shore","S_Shelf","S_Shore")

      CGI_rnd_regionMeans$Data<-paste("Random CpGs (", length(CpG_list),")", sep="")

      #Combine with real data
      Resort_hits_featureMeans$Data<-paste("Blood Brain Correlated CpGs (", length(CpG_list),")", sep="")  
      Resort_hits_featureMeans$Probe_count_SD<-0
      Resort_hits_featureMeans<-rbind(Resort_hits_featureMeans,CGI_rnd_regionMeans)

      Resort_hits_featureMeans$Feature<-factor(Resort_hits_featureMeans$Feature,
                                               levels=c("N_Shelf","N_Shore","Island","S_Shore","S_Shelf","None"))

      Resort_hits_featureMeans$Color<-sapply(1:nrow(Resort_hits_featureMeans), function(x) {
        paste(Resort_hits_featureMeans$Feature[x],Resort_hits_featureMeans$Data[x], sep=":")})

        levels(Resort_hits_featureMeans$Feature)<-c("N. Shelf","N. Shore","Island","S. Shore", "S. Shelf","None")
        CGI<-ggplot(Resort_hits_featureMeans, aes(Feature, Probe_Count, fill=Color, group=Data))+
              geom_bar(position=position_dodge(width=0.9),stat="identity", color="black")+theme_bw()+
         scale_fill_manual(values=c("#66bd63","#a1d99b","#999999","#f2f2f2","#74add1","#abd9e9","#feb24c","#ffeda0",
                                         "#74add1","#abd9e9","#feb24c","#ffeda0"))+
              geom_errorbar(aes(ymax = Probe_Count + Probe_count_SD, ymin=Probe_Count - Probe_count_SD),
                            width=0.25,position=position_dodge(width=0.9))+ylab("Probe Count")+
        theme(axis.text = element_text(size = 12),
              axis.title = element_text(size = 14),
              legend.text = element_text(size = 12))

    # Plot
      grid.arrange(Gene, CGI, ncol=1)


    ##Statistics
      Gene_hits_PrbCnt<-Gene_hits_regionMeans$Probe_Count[grep("Blood", Gene_hits_regionMeans$Data)]
      Gene_rnd_PrbCnt<-Gene_hits_regionMeans$Probe_Count[grep("Random", Gene_hits_regionMeans$Data)]
      Resort_hits_PrbCnt<-Resort_hits_featureMeans$Probe_Count[grep("Blood", Resort_hits_featureMeans$Data)]
      Resort_rnd_PrbCnt<-Resort_hits_featureMeans$Probe_Count[grep("Random", Resort_hits_featureMeans$Data)]

      Gene_hits_Percent<-(Gene_hits_PrbCnt/sum(Gene_hits_PrbCnt))*100
      Gene_rnd_Percent<-(Gene_rnd_PrbCnt/sum(Gene_rnd_PrbCnt))*100
      Resort_hits_Percent<-(Resort_hits_PrbCnt/sum(Resort_hits_PrbCnt))*100
      Resort_rnd_Percent<-(Resort_rnd_PrbCnt/sum(Resort_rnd_PrbCnt))*100

    name<-c(as.character(Resort_hits_featureMeans$Feature)[1:6], as.character(Gene_hits_regionMeans$Region)[1:4])
      Hits<-c(Resort_hits_Percent, Gene_hits_Percent)
      rnd<-c(Resort_rnd_Percent, Gene_rnd_Percent)
      Resort_fisher<-lapply(1:length(Resort_hits_Percent), function(x) {
        data<-matrix(c(Resort_hits_Percent[x], 100-Resort_hits_Percent[x],
                       Resort_rnd_Percent[x], 100-Resort_rnd_Percent[x]),
                     ncol=2, byrow=T)
        fisher.test(round((data/100)*length(CpG_list)))})
      names(Resort_fisher)<-as.character(Resort_hits_featureMeans$Feature)[1:6]
      Gene_fisher<-lapply(1:length(Gene_hits_Percent), function(x) {
        data<-matrix(c(Gene_hits_Percent[x], 100-Gene_hits_Percent[x],
                       Gene_rnd_Percent[x], 100-Gene_rnd_Percent[x]),
                     ncol=2, byrow=T)
        fisher.test(round((data/100)*length(CpG_list)))})
      names(Gene_fisher)<-as.character(Gene_hits_regionMeans$Region)[1:4]
      Fisher<-data.frame(Feature=c(names(Resort_fisher), names(Gene_fisher)),
                         Pval=c(sapply(1:length(Resort_fisher), function(x) round(Resort_fisher[[x]]$p.value,4)),
                                sapply(1:length(Gene_fisher), function(x) round(Gene_fisher[[x]]$p.value,4))))
      Fisher$FDR<-c(p.adjust(Fisher$Pval[1:6], method="fdr", n=6),
                    p.adjust(Fisher$Pval[7:10], method="fdr", n=4))
      Fisher$sig<-sapply(1:nrow(Fisher), function(x) {if(Fisher$FDR[x]>0.05){""}else{
        if(Fisher$FDR[x]>0.01){"*"}else{
          if(Fisher$FDR[x]>0.0001){"**"}else{"***"}
        }}})

      Fisher}

## informative
Feature_Bar_Plot(Cor_CpGs)
Feature_Bar_Plot(negCor_CpGs)

## overlap
Feature_Bar_Plot(pos_overlap)
Feature_Bar_Plot(neg_overlap)
```