---
title: "Validation_dataset"
author: "redgar"
date: '2015-03-11'
output: pdf_document
---

Libraries
```{r}
setwd("~/Documents/Blood_Brain/")
```

Load GSE59685 Beta values 
```{r}
GSE59685<- read.csv("Validation_GSE59685/GSE59685_betas.csv", skip=5)
```

#Validation Data
```{r}
load("Validation_GSE59685/GSE59685.RData")
```


Download GEO meta data
```{r}
library(GEOmetadb)
getSQLiteFile()
con <- dbConnect(SQLite(), "GEOmetadb.sqlite")
dbListFields(con, "gsm")
  
x<-dbGetQuery(con, "select title,series_id,gsm,source_name_ch1,characteristics_ch1 from gsm where gpl='GPL13534'")
meta<-x[which(x$series_id=="GSE59685"),]

meta$Subject<-unlist(sapply(1:nrow(meta), function(x){
  gsub("subjectid: ","",strsplit(meta$characteristics_ch1[x], ";\t")[[1]][1], fixed = T) # always field 2
}))
meta$barcode<-unlist(sapply(1:nrow(meta), function(x){
  gsub("barcode: ","",strsplit(meta$characteristics_ch1[x], ";\t")[[1]][2], fixed = T) # always field 2
}))
meta$ad.disease.status<-unlist(sapply(1:nrow(meta), function(x){
  gsub("ad.disease.status: ","",strsplit(meta$characteristics_ch1[x], ";\t")[[1]][3], fixed = T) # always field 2
}))
meta$braak.stage<-unlist(sapply(1:nrow(meta), function(x){
  gsub("braak.stage: ","",strsplit(meta$characteristics_ch1[x], ";\t")[[1]][4], fixed = T) # always field 2
}))
meta$Sex<-unlist(sapply(1:nrow(meta), function(x){
  gsub("Sex: ","",strsplit(meta$characteristics_ch1[x], ";\t")[[1]][5], fixed = T) # always field 2
}))
meta$age.blood<-unlist(sapply(1:nrow(meta), function(x){
  gsub("age.blood: ","",strsplit(meta$characteristics_ch1[x], ";\t")[[1]][6], fixed = T) # always field 2
}))
meta$age.brain<-unlist(sapply(1:nrow(meta), function(x){
  gsub("age.brain: ","",strsplit(meta$characteristics_ch1[x], ";\t")[[1]][7], fixed = T) # always field 2
}))
meta$Tissue<-unlist(sapply(1:nrow(meta), function(x){
  gsub("source tissue: ","",strsplit(meta$characteristics_ch1[x], ";\t")[[1]][8], fixed = T) # always field 2
}))

meta$description<-NULL
meta$source_name_ch1<-NULL
meta$characteristics_ch1<-NULL
meta$title<-NULL
save(meta, file='Meta_data_GSE59685.Rdata')
```

#Samples which are matched
```{r}
Blood<-subset(meta, Tissue=="whole blood")
Brain<-subset(meta, Tissue!="whole blood")

Brain_matched<-Brain[which(Brain$Subject%in%Blood$Subject),]
Blood_matched<-Blood[which(Blood$Subject%in%Brain_matched$Subject),]
Meta_matched<-rbind(Brain_matched,Blood_matched)
tapply(Brain_matched$Subject, Brain_matched$Tissue, function(x) length(unique(x)))#71 individuals will all 4 brain regions

save(Meta_matched, file='Meta_matched_GSE59685.Rdata')
```


## Pull out Betas of matched samples (did on cake actually)
```{r}
# may just do everything on cake since it is still 366 matched samples
```

